project:
  type: book

book:
  title: "BMM Developer Notes"
  chapters:
    - index.qmd
    - setup.qmd
    - git-workflow.qmd
    - bmm-architecture.qmd
    - example-model.qmd
    - add-new-model.qmd
  navbar:
    background: primary
    search: true
    left:
       - text: Functions
         href: ../reference/index.html
       - text: Articles
         href: ../articles/index.html
       - text: Changelog
         href: ../news/index.html
       - text: Develop
         href: ../dev-notes/index.html


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-line-numbers: true
    code-fold: true
    grid:
       body-width: 900px
  pdf:
    documentclass: scrreprt

editor: visual

